### PR TITLE
add ExprUsesArgs analysis

### PR DESCRIPTION
**Pull request by yihozhang**
This analysis returns a set of variables used by an expression. Users of this analysis need to explicitly place demands on the expression they want to run this analysis on.

### CODE REVIEW

**Comment by oflatt** [comment]
Why does this PR require using a set? Not sure what it is used for yet.
Could you do a relation `(relation ExprUsesVar (Expr Expr))`?

**Comment by yihozhang** [comment]
There are several reasons for this:
* I need to collect a list `FV` of all free variables of an expression, and add `FV` to the input context of `let-inlining`. Collecting all values of a column in a container is less straightforward than just having a `set` as output.
* There was a typo in the original analysis. The merge function for `ExprUsesArgs` should be `set-intersect`, otherwise a constant may use variables if it is merged with `x-x`, etc. `relation` cannot do this.

**Comment by oflatt** [comment]
So this is more like a `ExprAlwaysUsesArgs` analysis? As in, it uses these arguments in all equivalent versions?

**Comment by oflatt** [comment]
I think we decided to close this, since we are changing it to extract a particular term that uses a particular set of arguments.

**Pull request closed without merging**
