### PR TITLE
Add ids to Allocs

### PR DESCRIPTION
**Pull request by rtjoa**
Add an `i64` field to `Alloc`, which should be uniquely assigned during translation.

### CODE REVIEW

**Comment by oflatt** [comment]
I think that we should make the allocations have unique ids in rust, not egglog
That way we don't need `i64-fresh!`

I'd also be a lot happier if we found a way to not have unique ids on the allocations, and use the expression that generated that allocation instead. But we'd need to think carefully about that

**Comment by rtjoa** [comment]
> I think that we should make the allocations have unique ids in rust, not egglog That way we don't need `i64-fresh!`

I originally did it from rust by adding a `next_alloc_id: i64` field to `DagTranslator`. However, we then have no way to atomically get the next id in egglog, which we need to do as we create `Alloc`s in `Subst`/`DoAddContext`.

> I'd also be a lot happier if we found a way to not have unique ids on the allocations, and use the expression that generated that allocation instead. But we'd need to think carefully about that

We could refer to allocs in a *child* context or a func call with this cell datatype:
```
type cell = InSameContext expr | InLoop in out expr | InFuncCall fn args expr
```
but we'd need another Context node type to refer to allocs in a parent context.

For now, I think unique ids is easiest our current plan as of last memory meeting.

**Comment by rtjoa** [comment]
Per discussion on Slack, assigned ids in Rust, as it's actually sound to have multiple ids per e-class: it just makes the analysis less precise.

**Review by oflatt — APPROVED** [review]
lgtm

**Pull request merged**
