### PR TITLE
get rid of dependency on filesystem

### PR DESCRIPTION
**Pull request by ryan-berger**

### CODE REVIEW

**Comment by ryan-berger** [comment]
@oflatt @ajpal we do need to wait for the nightly to run tonight, but it works well on my machine (which is nearly identical to the nightly box)

**Comment by ryan-berger** [comment]
@oflatt Nightlies seem to be broken actually. `benchmarks/passing/bril/float/conjugate-gradient.ll`. But looks like it happens on main too

**Review by oflatt — APPROVED** [review]
This looks great!
I see that the chart is broken in main, and nightly is broken too. Lets hold off on merging, we'll fix it ASAP

**Comment by oflatt** [comment]
Works!

**Pull request merged**
